[package]
name = "major-project"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = "0.8.4"
symphonia = { version = "0.5.4", features = ["all-codecs"] }
tokio = { version = "1.47.1", features = ["full"] }
